package org.mayoclinic.modeling.xsd;

/**
 * Created by Bryn on 2/5/2016.
 */
public class XsdImportOptions {
    public XsdImportOptions() {
        // By default, do not generate types for restrictions of simple types
        generateSimpleTypeRestrictions = false;
        generateEmptyComplexTypes = false;
        publisher = "Generated by Xsd-to-FHIR";
        publisherContact = "Visit the Github repository for more information";
        publisherUrl = "https://github.com/cts2/CTS2-to-FHIR";
    }

    private boolean generateSimpleTypeRestrictions;
    public boolean getGenerateSimpleTypeRestrictions() {
        return generateSimpleTypeRestrictions;
    }

    public void setGenerateSimpleTypeRestrictions(boolean value) {
        generateSimpleTypeRestrictions = value;
    }

    private boolean generateEmptyComplexTypes;
    public boolean getGenerateEmptyComplexTypes() {
        return generateEmptyComplexTypes;
    }

    public void setGenerateEmptyComplexTypes(boolean value) {
        generateEmptyComplexTypes = value;
    }

    private String publisher;
    public String getPublisher() {
        return publisher;
    }

    private void setPublisher(String value) {
        publisher = value;
    }

    private String publisherContact;
    public String getPublisherContact() {
        return publisherContact;
    }

    private void setPublisherContact(String value) {
        publisherContact = value;
    }

    private String publisherUrl;
    public String getPublisherUrl() {
        return publisherUrl;
    }

    private void setPublisherUrl(String value) {
        publisherUrl = value;
    }
}
